### ISSUE TITLE
Possible conflict with CWE V8.1?

### ISSUE THREAD

**Issue by Drflash55** [X-Hax/sa2-mod-loader#15]
I was able to play CWE V8.1 (Chao World Extended, created by DarkyBenji and the rest of them) just fine on SA2 a while ago, but when I went to go play it today when I loaded the ModLoader, it downloaded an update, and then it seems to keep breaking afterwards (game crashes before the SEGA logo shows). I don't know if the recent commit (as of now, it was an hour ago) is causing something to go wrong with it.

I've tested it out without CWE and with it, and it seems to run fine if CWE is not currently loaded. Otherwise, it crashes.
I'd like some help with this so I can know what's going on.

UPDATE (15:48 UTC -5)
------
It seems that this crashed gets bypassed if I allow sonic2app.exe to run as an Administrator, but otherwise, it keeps crashing without it.
Not sure why this is the case, but at least I have a method to get around the crashing issue I'm still experiencing.

**Comment by RinMaru** [comment]
no issues on my end

**Comment by MainMemory** [comment]
It crashed for me without CWE. I patched it so it shouldn't outright crash anymore.
