### ISSUE TITLE
Skip Intro function breaks loading screen mods

### ISSUE THREAD

**Issue by ViperAcidZX** [X-Hax/sa2-mod-loader#32]
I've been using the [Loading Screens Are Stupid](https://gamebanana.com/mods/48910) mod before to get rid of the loading screen text and Omochao tips since my PC is fast enough to make loading times to even read the texts almost non-existent/make the game more like the GameCube version's loading screens and the mod worked fine, but after enabling the "Skip Intro" function in the Mod Loader, the loading screen tips still appear. I have tried also installing [No Loading Screen Tips](https://gamebanana.com/mods/33159) mod and that doesn't work unless I turn off Skip Intro.

**Comment by Sora-yx** [comment]
The last mod loader update fb3a3a98a5ff130b957acbfd3682d14d70038d94 added a code to disable loading tips, this one will work with the skip intro option.
