### ISSUE TITLE
Crash when loading a stage via debug

### ISSUE THREAD

**Issue by ElectroNuke** [X-Hax/sa2-mod-loader#39]
After the latest auto-update, I tried loading a stage via the new-ish debug tab, but not even the two logos pop up. My window literally freezes on a black screen. Can you confirm that this is a real issue? Thanks.

**Comment by kellsnc** [comment]
Works fine for me.
You'll have faster support on the discord server by the way ^^

**Comment by Sora-yx** [comment]
Since there is no answer, I'm gonna assume this is no longer an issue, feel free to re open if needed.
