### ISSUE TITLE
SA2 Mod Manager Upgrade Error

### ISSUE THREAD

**Issue by SonicThomasGamer** [X-Hax/sa2-mod-loader#48]
Am I doing something wrong?

**Steps Taken**

Opened SA2 mod manager normally and as admin

Got an update notification 

click okay

SA2 mod manager is being deprecated popup 

click on Get the new SA Mod Manager 

SA2 mod manger : Unable to retrieve update information

![Screenshot (244)](https://github.com/X-Hax/sa2-mod-loader/assets/133928350/edf38c10-41f8-4823-9d8b-047d5204dce4)

**Comment by SAWSYSTEM** [comment]
having the exact same issue with the exact same steps taken, not sure whats going on. for some reason the only release available on here is from 2017??

**Comment by SonicThomasGamer** [comment]
> If you can't update with the tool, you can download the new Manager manually [here.](https://github.com/X-Hax/SA-Mod-Manager/releases/latest)

**Say what?**

I thought that was only SADX modloader, I had no idea it actually merged and it supported SA2

_Thanks buddy_  
![1237320_20240310183916_1](https://github.com/X-Hax/sa2-mod-loader/assets/133928350/a2a4f022-1e24-46e3-aefa-67e13490ee93)
