### ISSUE TITLE
"Mod loader could not be read"

### ISSUE THREAD

**Issue by XPSus** [X-Hax/sa2-mod-loader#52]
![image_2024-05-23_140612631](https://github.com/X-Hax/sa2-mod-loader/assets/169675698/db18e1cd-cbba-4925-a6da-8ec54a3f2c7e)
**Description**

**Steps Taken**

**Expected behavior**

**Comment by Sora-yx** [comment]
Your Mod Loader isn't up to date, new versions no longer use sa2modloader.ini.
