### ISSUE TITLE
Sonic Adventure 2 Crash

### ISSUE THREAD

**Issue by SwiftM0nkey** [X-Hax/sa2-mod-loader#53]
While using the Archipelago Mod (which allows many different players to all play their own single player games and send "checks" to other games), if the Biolizard fight with Shadow is dealt the final blow as these "checks" from other games are sent, the game will crash. This happens as long as the check has been sent after dealing the final blow but before Shadow does his victory pose. 

1. Go to Biolizard fight with Shadow
2. Get the Boss to one hit remaining
3. Pause the  game
4. Make sure another player using the Archipelago mod sends a lot of checks
5. Finish the boss

Obviously the game should not be crashing here, as it does not interfere with any other part of the game.
[CrashDump_04_06_2024_01_15_56.dmp](https://github.com/user-attachments/files/15543051/CrashDump_04_06_2024_01_15_56.dmp)
[ModList_06_04_2024_01_15_57.json](https://github.com/user-attachments/files/15543052/ModList_06_04_2024_01_15_57.json)
![image](https://github.com/X-Hax/sa2-mod-loader/assets/62174587/fc591abe-4c5c-4181-9d02-cf9eab54e9ea)

**Comment by MainMemory** [comment]
Isn't this a bug in the Archipelago mod, not in the mod loader itself?
