### ISSUE TITLE
The mod No LoD, that disables the Level of Detail models for Sonic and Shadow no longer works.

### ISSUE THREAD

**Issue by shadowstardx** [X-Hax/sa2-mod-loader#58]
![download](https://github.com/user-attachments/assets/b9f6f477-a53a-4e80-b086-e7110fed2573)
![NoLoD](https://github.com/user-attachments/assets/41fca756-5dee-44ee-ba3c-64cb6424769d)
![LoD](https://github.com/user-attachments/assets/c9cfde12-d93c-4d51-afb2-d54c06144693)

**Comment by shadowstardx** [comment]
keeps saying DLL not found etc, reinstalled game

**Comment by Sora-yx** [comment]
This has nothing to do with the Mod Loader. Either the user uploaded the DLL in debug and if so, they will have to fix it, or you are missing the Visual c++ runtime dependencies. Additionally, it's also possible that the DLL is missing in the files due to a corrupted install.
