### ISSUE TITLE
Mod Loader Won't Install for Sonic Adventure 2

### ISSUE THREAD

**Issue by Iggyminious** [X-Hax/sa2-mod-loader#59]
**Description**
Whenever I try to install the mod loader for Sonic Adventure 2 using the new SA Mod Manager, it says, "Failed to detect Game Directory path. Please set the path in the Manager Config and make sure to select a folder where sonic.exe is installed." However, sonic.exe is used for SADX and not SA2, which uses sonic2app.exe, so even though I do have a proper path to the Sonic Adventure 2 folder, it still won't install.

**Steps Taken**
1. Go to 'Mod Loader'
2. Click on 'Install Mod Loader'
3. See error

**Expected behavior**
When selecting "Install Mod Loader" it should either install the mod loader or say to select a folder where sonic2app.exe is installed.

**Comment by Sora-yx** [comment]
This is the wrong repo, you should use the SA Mod Manager one.
An issue already exist there, please check what is answered:
https://github.com/X-Hax/SA-Mod-Manager/issues/184
