### ISSUE TITLE
I hope I'm not wasting anybody's time

### ISSUE THREAD

**Issue by SteelGrip05** [X-Hax/sa2-mod-loader#65]
[21_29_51_Dump_Sonic_lvl13.dmp](https://github.com/user-attachments/files/16987360/21_29_51_Dump_Sonic_lvl13.dmp)
[21_29_51_extra_info_Sonic_lvl13.txt](https://github.com/user-attachments/files/16987364/21_29_51_extra_info_Sonic_lvl13.txt)
[21_29_51_ModList_Sonic_lvl13.json](https://github.com/user-attachments/files/16987366/21_29_51_ModList_Sonic_lvl13.json)

No matter how I try to enter any stage (with any character) in either story mode (I know story's not supposed to work, but I wanted to try everything) or from stage select, the game gets half a second into loading & then crashes.

To recreate this: Select a stage from any method, the game will then crash.

Idk if there's something I'm doing wrong, but I've tried ensuring the mod order is correct & ensuring that specific settings are enabled/disabled, & even downloaded/installed DXVK to try & help, but nothing seems to be working. I am genuinely sorry if this winds up being a waste of time, I just want to play a modified version of an old game where a talking blue hedgehog throws himself at robots...

(I also added the files deemed "optional" by the Modern SA2 mod with no change in results midway through making this, it didn't work...)

**Comment by Sora-yx** [comment]
This has nothing to do with the Mod Loader, that's an issue with your mod list / codes. Disable your mods one by one and find which one is the culprit.
