### ISSUE TITLE
Mods Don't Appear When I Open SA2

### ISSUE THREAD

**Issue by Trippie-Thr3at** [X-Hax/sa2-mod-loader#76]
**Description**
Whenever i open up SA2 with my mod loader, i'm just playing SA2 without mods. I tried searching for the problem but i didnt find anything.

I would open up the mod manager, check some of my mods, then open up the game, but the screen also isnt covering the whole screen for some reason but when i load in, there isnt any sign of my mods.

**Comment by PiKeyAr** [comment]
Check for a folder called `SAManager` in the location where your `SAModManager.exe` is. If it exists, delete it and restart the Manager. You might need to reconfigure your games or mods.
